/* The following code was generated by JFlex 1.6.1 */

package lexer;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/home/lucas/NetBeansProjects/Analisador /src/lexer/arquivo.jflex</tt>
 */
public class AnalisadorLexo {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\2\3\2\0\1\3\22\0\1\3\1\53\3\0\1\56\1\51"+
    "\1\0\1\42\1\43\1\2\1\7\1\0\1\6\1\11\1\1\1\5"+
    "\11\10\1\0\1\57\1\54\1\52\1\55\2\0\4\4\1\12\25\4"+
    "\1\46\1\0\1\47\1\0\1\4\1\0\1\17\1\14\1\21\1\23"+
    "\1\13\1\26\1\41\1\34\1\30\1\4\1\37\1\16\1\36\1\20"+
    "\1\15\1\32\1\4\1\27\1\22\1\25\1\33\1\35\1\31\1\24"+
    "\1\40\1\4\1\44\1\50\1\45\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\15\5\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\2\1\1\17\1\20\1\21\1\22\1\23\1\24\1\0"+
    "\2\25\1\17\13\5\1\26\7\5\1\27\5\5\1\30"+
    "\1\31\1\32\1\20\1\33\1\34\2\0\4\5\1\35"+
    "\11\5\1\36\4\5\1\37\5\5\1\40\1\41\1\42"+
    "\4\5\1\43\4\5\1\44\1\5\1\45\12\5\1\46"+
    "\1\41\2\5\1\47\1\50\2\5\1\51\1\5\1\52"+
    "\1\53\6\5\1\54\2\5\3\41\2\5\1\55\1\56"+
    "\1\5\1\57\1\5\1\60\2\5\1\61\2\5\1\62"+
    "\1\63\1\64\1\65\1\66\3\5\1\67\4\5\1\70"+
    "\1\5\1\71\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\60\0\300\0\220\0\220"+
    "\0\60\0\360\0\u0120\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210"+
    "\0\u0240\0\u0270\0\u02a0\0\u02d0\0\u0300\0\u0330\0\60\0\60"+
    "\0\60\0\60\0\60\0\60\0\u0360\0\u0390\0\u03c0\0\u03f0"+
    "\0\u0420\0\u0450\0\60\0\60\0\u0480\0\u04b0\0\u04e0\0\60"+
    "\0\u0510\0\u0540\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630\0\u0660"+
    "\0\u0690\0\u06c0\0\u06f0\0\300\0\u0720\0\u0750\0\u0780\0\u07b0"+
    "\0\u07e0\0\u0810\0\u0840\0\300\0\u0870\0\u08a0\0\u08d0\0\u0900"+
    "\0\u0930\0\60\0\60\0\60\0\60\0\60\0\60\0\u0960"+
    "\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\300\0\u0a80\0\u0ab0"+
    "\0\u0ae0\0\u0b10\0\u0b40\0\u0b70\0\u0ba0\0\u0bd0\0\u0c00\0\300"+
    "\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20\0\u0d50\0\u0d80"+
    "\0\u0db0\0\u0de0\0\60\0\u0e10\0\300\0\u0e40\0\u0e70\0\u0ea0"+
    "\0\u0ed0\0\300\0\u0f00\0\u0f30\0\u0f60\0\u0f90\0\300\0\u0fc0"+
    "\0\300\0\u0ff0\0\u1020\0\u1050\0\u1080\0\u10b0\0\u10e0\0\u1110"+
    "\0\u1140\0\u1170\0\u11a0\0\300\0\u11d0\0\u1200\0\u1230\0\300"+
    "\0\300\0\u1260\0\u1290\0\300\0\u12c0\0\u12f0\0\300\0\u1320"+
    "\0\u1350\0\u1380\0\u13b0\0\u13e0\0\u1410\0\300\0\u1440\0\u1470"+
    "\0\u14a0\0\60\0\u14d0\0\u1500\0\u1530\0\300\0\300\0\u1560"+
    "\0\300\0\u1590\0\300\0\u15c0\0\u15f0\0\300\0\u1620\0\u1650"+
    "\0\300\0\300\0\300\0\300\0\300\0\u1680\0\u16b0\0\u16e0"+
    "\0\300\0\u1710\0\u1740\0\u1770\0\u17a0\0\300\0\u17d0\0\300"+
    "\0\300";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\2\1\7\1\10"+
    "\1\2\1\11\1\6\1\12\1\13\3\6\1\14\1\15"+
    "\1\16\1\17\1\6\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\2\6\1\26\4\6\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\62\0\1\45\2\0\1\46\2\0\1\47"+
    "\41\0\1\50\12\0\1\46\2\0\1\47\41\0\1\50"+
    "\11\0\2\6\2\0\1\6\1\0\30\6\22\0\2\6"+
    "\2\0\1\6\1\0\4\6\1\51\5\6\1\52\15\6"+
    "\22\0\2\6\2\0\1\6\1\0\3\6\1\53\11\6"+
    "\1\54\12\6\22\0\2\6\2\0\1\6\1\0\1\6"+
    "\1\55\26\6\22\0\2\6\2\0\1\6\1\0\4\6"+
    "\1\56\1\57\22\6\22\0\2\6\2\0\1\6\1\0"+
    "\13\6\1\60\3\6\1\61\1\6\1\62\6\6\22\0"+
    "\2\6\2\0\1\6\1\0\1\6\1\63\1\6\1\64"+
    "\24\6\22\0\2\6\2\0\1\6\1\0\15\6\1\65"+
    "\4\6\1\66\5\6\22\0\2\6\2\0\1\6\1\0"+
    "\3\6\1\67\1\6\1\70\10\6\1\71\11\6\22\0"+
    "\2\6\2\0\1\6\1\0\1\6\1\72\26\6\22\0"+
    "\2\6\2\0\1\6\1\0\6\6\1\73\5\6\1\74"+
    "\7\6\1\75\3\6\22\0\2\6\2\0\1\6\1\0"+
    "\22\6\1\76\5\6\22\0\2\6\2\0\1\6\1\0"+
    "\5\6\1\77\13\6\1\100\6\6\22\0\2\6\2\0"+
    "\1\6\1\0\3\6\1\101\24\6\66\0\1\102\60\0"+
    "\1\103\60\0\1\104\57\0\1\105\57\0\1\106\57\0"+
    "\1\107\5\0\2\45\1\110\55\45\11\0\1\111\53\0"+
    "\1\47\2\0\1\47\1\111\52\0\2\6\2\0\1\6"+
    "\1\0\10\6\1\112\17\6\22\0\2\6\2\0\1\6"+
    "\1\0\13\6\1\113\14\6\22\0\2\6\2\0\1\6"+
    "\1\0\3\6\1\114\24\6\22\0\2\6\2\0\1\6"+
    "\1\0\1\6\1\115\26\6\22\0\2\6\2\0\1\6"+
    "\1\0\17\6\1\116\10\6\22\0\2\6\2\0\1\6"+
    "\1\0\5\6\1\117\22\6\22\0\2\6\2\0\1\6"+
    "\1\0\10\6\1\120\17\6\22\0\2\6\2\0\1\6"+
    "\1\0\5\6\1\121\22\6\22\0\2\6\2\0\1\6"+
    "\1\0\16\6\1\122\11\6\22\0\2\6\2\0\1\6"+
    "\1\0\20\6\1\123\7\6\22\0\2\6\2\0\1\6"+
    "\1\0\14\6\1\124\13\6\22\0\2\6\2\0\1\6"+
    "\1\0\21\6\1\125\6\6\22\0\2\6\2\0\1\6"+
    "\1\0\15\6\1\126\1\127\11\6\22\0\2\6\2\0"+
    "\1\6\1\0\15\6\1\130\12\6\22\0\2\6\2\0"+
    "\1\6\1\0\4\6\1\131\23\6\22\0\2\6\2\0"+
    "\1\6\1\0\6\6\1\132\21\6\22\0\2\6\2\0"+
    "\1\6\1\0\13\6\1\133\14\6\22\0\2\6\2\0"+
    "\1\6\1\0\10\6\1\134\2\6\1\135\14\6\22\0"+
    "\2\6\2\0\1\6\1\0\20\6\1\136\7\6\22\0"+
    "\2\6\2\0\1\6\1\0\16\6\1\137\11\6\22\0"+
    "\2\6\2\0\1\6\1\0\7\6\1\140\20\6\22\0"+
    "\2\6\2\0\1\6\1\0\2\6\1\141\25\6\22\0"+
    "\2\6\2\0\1\6\1\0\16\6\1\142\11\6\16\0"+
    "\1\45\1\143\1\110\55\45\5\0\1\144\2\0\1\144"+
    "\53\0\2\6\2\0\1\6\1\0\1\6\1\145\26\6"+
    "\22\0\2\6\2\0\1\6\1\0\1\6\1\146\26\6"+
    "\22\0\2\6\2\0\1\6\1\0\4\6\1\147\23\6"+
    "\22\0\2\6\2\0\1\6\1\0\5\6\1\150\22\6"+
    "\22\0\2\6\2\0\1\6\1\0\10\6\1\151\17\6"+
    "\22\0\2\6\2\0\1\6\1\0\1\6\1\152\26\6"+
    "\22\0\2\6\2\0\1\6\1\0\13\6\1\153\14\6"+
    "\22\0\2\6\2\0\1\6\1\0\13\6\1\154\14\6"+
    "\22\0\2\6\2\0\1\6\1\0\1\6\1\155\26\6"+
    "\22\0\2\6\2\0\1\6\1\0\5\6\1\156\22\6"+
    "\22\0\2\6\2\0\1\6\1\0\1\6\1\157\26\6"+
    "\22\0\2\6\2\0\1\6\1\0\3\6\1\160\24\6"+
    "\22\0\2\6\2\0\1\6\1\0\10\6\1\161\17\6"+
    "\22\0\2\6\2\0\1\6\1\0\10\6\1\162\17\6"+
    "\22\0\2\6\2\0\1\6\1\0\5\6\1\163\22\6"+
    "\22\0\2\6\2\0\1\6\1\0\21\6\1\164\6\6"+
    "\22\0\2\6\2\0\1\6\1\0\13\6\1\165\14\6"+
    "\22\0\2\6\2\0\1\6\1\0\1\6\1\166\26\6"+
    "\22\0\2\6\2\0\1\6\1\0\3\6\1\167\1\170"+
    "\23\6\22\0\2\6\2\0\1\6\1\0\4\6\1\171"+
    "\23\6\22\0\2\6\2\0\1\6\1\0\25\6\1\172"+
    "\2\6\22\0\2\6\2\0\1\6\1\0\4\6\1\173"+
    "\23\6\22\0\2\6\2\0\1\6\1\0\11\6\1\174"+
    "\16\6\23\0\1\144\2\0\1\144\1\0\2\175\50\0"+
    "\2\6\2\0\1\6\1\0\6\6\1\176\21\6\22\0"+
    "\2\6\2\0\1\6\1\0\1\6\1\177\26\6\22\0"+
    "\2\6\2\0\1\6\1\0\25\6\1\200\2\6\22\0"+
    "\2\6\2\0\1\6\1\0\10\6\1\201\17\6\22\0"+
    "\2\6\2\0\1\6\1\0\16\6\1\202\11\6\22\0"+
    "\2\6\2\0\1\6\1\0\7\6\1\203\20\6\22\0"+
    "\2\6\2\0\1\6\1\0\15\6\1\204\12\6\22\0"+
    "\2\6\2\0\1\6\1\0\21\6\1\205\6\6\22\0"+
    "\2\6\2\0\1\6\1\0\17\6\1\206\10\6\22\0"+
    "\2\6\2\0\1\6\1\0\1\6\1\207\26\6\22\0"+
    "\2\6\2\0\1\6\1\0\4\6\1\210\23\6\22\0"+
    "\2\6\2\0\1\6\1\0\15\6\1\211\12\6\22\0"+
    "\2\6\2\0\1\6\1\0\5\6\1\212\22\6\22\0"+
    "\2\6\2\0\1\6\1\0\15\6\1\213\12\6\22\0"+
    "\2\6\2\0\1\6\1\0\15\6\1\214\12\6\22\0"+
    "\2\6\2\0\1\6\1\0\1\6\1\215\26\6\22\0"+
    "\2\6\2\0\1\6\1\0\1\6\1\216\26\6\22\0"+
    "\2\6\2\0\1\6\1\0\5\6\1\217\22\6\22\0"+
    "\2\6\2\0\1\6\1\0\16\6\1\220\11\6\17\0"+
    "\2\221\2\0\1\222\2\221\1\223\53\0\2\6\2\0"+
    "\1\6\1\0\11\6\1\224\16\6\22\0\2\6\2\0"+
    "\1\6\1\0\5\6\1\225\22\6\22\0\2\6\2\0"+
    "\1\6\1\0\7\6\1\226\20\6\22\0\2\6\2\0"+
    "\1\6\1\0\22\6\1\227\5\6\22\0\2\6\2\0"+
    "\1\6\1\0\4\6\1\230\23\6\22\0\2\6\2\0"+
    "\1\6\1\0\10\6\1\231\17\6\22\0\2\6\2\0"+
    "\1\6\1\0\4\6\1\232\23\6\22\0\2\6\2\0"+
    "\1\6\1\0\6\6\1\233\21\6\22\0\2\6\2\0"+
    "\1\6\1\0\6\6\1\234\21\6\22\0\2\6\2\0"+
    "\1\6\1\0\14\6\1\235\13\6\22\0\2\6\2\0"+
    "\1\6\1\0\13\6\1\236\14\6\22\0\2\6\2\0"+
    "\1\6\1\0\24\6\1\237\3\6\22\0\2\6\2\0"+
    "\1\6\1\0\27\6\1\240\22\0\2\6\2\0\1\6"+
    "\1\0\7\6\1\241\20\6\23\0\1\222\2\0\1\223"+
    "\54\0\1\223\2\0\1\223\53\0\2\6\2\0\1\6"+
    "\1\0\10\6\1\242\17\6\22\0\2\6\2\0\1\6"+
    "\1\0\6\6\1\243\21\6\22\0\2\6\2\0\1\6"+
    "\1\0\13\6\1\244\14\6\22\0\2\6\2\0\1\6"+
    "\1\0\26\6\1\245\1\6\22\0\2\6\2\0\1\6"+
    "\1\0\7\6\1\246\20\6\22\0\2\6\2\0\1\6"+
    "\1\0\5\6\1\247\22\6\22\0\2\6\2\0\1\6"+
    "\1\0\1\6\1\250\26\6\22\0\2\6\2\0\1\6"+
    "\1\0\1\6\1\251\26\6\22\0\2\6\2\0\1\6"+
    "\1\0\1\6\1\252\26\6\22\0\2\6\2\0\1\6"+
    "\1\0\7\6\1\253\20\6\22\0\2\6\2\0\1\6"+
    "\1\0\6\6\1\254\21\6\22\0\2\6\2\0\1\6"+
    "\1\0\3\6\1\255\24\6\22\0\2\6\2\0\1\6"+
    "\1\0\1\6\1\256\26\6\22\0\2\6\2\0\1\6"+
    "\1\0\13\6\1\257\14\6\22\0\2\6\2\0\1\6"+
    "\1\0\14\6\1\260\13\6\22\0\2\6\2\0\1\6"+
    "\1\0\10\6\1\261\17\6\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6144];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\3\1\1\11\15\1\6\11"+
    "\6\1\2\11\1\0\2\1\1\11\31\1\6\11\2\0"+
    "\31\1\1\11\56\1\1\11\37\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  
 public static void token(String yytex) throws IOException {
        File file = new File("").getAbsoluteFile();
        //"/src/lexer/Arquivo.txt";  

        File arq = new File(file + "/src/lexer/Tokens.txt");

        //neste ponto criamos o arquivo fisicamente
        arq.createNewFile();

        //Devemos passar no construtor do FileWriter qual arquivo
        // vamos manipular.
        // Esse construtor aceita dois tipos de parâmetros,
        // File ou String.
        //O parâmetro true indica que reescrevemos no arquivo
        // sem apagar o que já existe.
        // O false apagaria o conteúdo do arquivo e escreveria
        // o novo conteúdo.
        // Se não usar o 2° parâmetro, ele por padrão será false.
        //O mais importante, essa linha abre o fluxo do arquivo 

        FileWriter fileWriter = new FileWriter(arq, true);
        PrintWriter printWriter = new PrintWriter(fileWriter);
        printWriter.println(yytex);
        //o método flush libera a escrita no arquivo
        printWriter.flush();

        //No final precisamos fechar o arquivo
        printWriter.close();

    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalisadorLexo(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 164) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.print(yytext());
            }
          case 59: break;
          case 2: 
            { System.out.println(" Op_divisão        -> " + yytext().toString());token(" Op_divisão    -> " + yytext());
            }
          case 60: break;
          case 3: 
            { System.out.println(" Op_multiplicação  -> " + yytext().toString());token(" Op_multiplicação -> " + yytext());
            }
          case 61: break;
          case 4: 
            { /* Fazer Nada */
            }
          case 62: break;
          case 5: 
            { System.out.println(" id                        -> " + yytext().toString());token(" id          -> " + yytext());
            }
          case 63: break;
          case 6: 
            { System.out.println(" Op_subtração      -> " + yytext().toString());token(" Op_subtração  -> " + yytext());
            }
          case 64: break;
          case 7: 
            { System.out.println(" Op_adção          -> " + yytext().toString());token(" Op_adção -> " + yytext());
            }
          case 65: break;
          case 8: 
            { System.out.println(" Ponto             -> " + yytext().toString());token(" Ponto       -> " + yytext());
            }
          case 66: break;
          case 9: 
            { System.out.println(" Abrepar           -> " + yytext().toString());token(" Abrepar     -> " + yytext());
            }
          case 67: break;
          case 10: 
            { System.out.println(" Fechapar          -> " + yytext().toString());token(" Fechapar    -> " + yytext());
            }
          case 68: break;
          case 11: 
            { System.out.println(" Abrechave         -> " + yytext().toString());token(" Abrechave   -> " + yytext());
            }
          case 69: break;
          case 12: 
            { System.out.println(" Fechachave        -> " + yytext().toString());token(" Fechachave  -> " + yytext());
            }
          case 70: break;
          case 13: 
            { System.out.println(" Abrecolc          -> " + yytext().toString());token(" Abrecolc    -> " + yytext());
            }
          case 71: break;
          case 14: 
            { System.out.println(" Fechacolc         -> " + yytext().toString());token(" Fechacolc   -> " + yytext());
            }
          case 72: break;
          case 15: 
            { System.out.println(" Atrib_            -> " + yytext().toString());token(" Atrib_      -> " + yytext());
            }
          case 73: break;
          case 16: 
            { System.out.println(" Op_diferente_de   -> " + yytext().toString());token(" Op_diferente_de -> " + yytext());
            }
          case 74: break;
          case 17: 
            { System.out.println(" Op_menor_que      -> " +yytext().toString());token(" Op_menor_que  -> " + yytext());
            }
          case 75: break;
          case 18: 
            { System.out.println(" Op_maior_que      -> " + yytext().toString());token(" Op_maior_que -> " + yytext());
            }
          case 76: break;
          case 19: 
            { System.out.println(" Op_mod            -> " + yytext().toString());token(" Op_mod        -> " + yytext());
            }
          case 77: break;
          case 20: 
            { System.out.println(" Term_ponto_e_virgula -> " + yytext().toString());token(" Term_ponto_e_virgula -> " + yytext());
            }
          case 78: break;
          case 21: 
            { System.out.println(" inteiro                   -> " + yytext().toString());token(" inteiro     -> " + yytext());
            }
          case 79: break;
          case 22: 
            { System.out.println(" DO           -> " +  yytext().toString());token(" DO         -> " + yytext());
            }
          case 80: break;
          case 23: 
            { System.out.println(" IF           -> " + yytext().toString());token(" IF          -> " + yytext());
            }
          case 81: break;
          case 24: 
            { System.out.println(" Op_ou             -> " + yytext().toString());token(" Op_ou       -> " + yytext());
            }
          case 82: break;
          case 25: 
            { System.out.println(" Op_e              -> " + yytext().toString());token(" Op_e        -> " + yytext());
            }
          case 83: break;
          case 26: 
            { System.out.println(" Op_igual_a        -> " + yytext().toString());token(" Op_igual_a  -> " + yytext());
            }
          case 84: break;
          case 27: 
            { System.out.println(" Op_menor_igual_a  -> " + yytext().toString());token(" Op_menor_igual_a -> " + yytext());
            }
          case 85: break;
          case 28: 
            { System.out.println(" Op_maior_igual_a  -> " + yytext().toString());token(" Op_maior_igual_a -> " + yytext());
            }
          case 86: break;
          case 29: 
            { System.out.println(" NEW          -> " + yytext().toString());token(" NEW         -> " + yytext());
            }
          case 87: break;
          case 30: 
            { System.out.println(" FOR          -> " + yytext().toString());token(" FOR         -> " + yytext());
            }
          case 88: break;
          case 31: 
            { System.out.println(" INT          -> " + yytext().toString());token(" INT         -> " + yytext());
            }
          case 89: break;
          case 32: 
            { System.out.println(" Comentario                -> " + yytext().toString());token(" Comentario  -> " + yytext());
            }
          case 90: break;
          case 33: 
            { System.out.println(" Float                     -> " + yytext().toString());token(" Float       -> " + yytext());
            }
          case 91: break;
          case 34: 
            { System.out.println(" ELSE         -> " + yytext().toString());token(" ELSE        -> " + yytext());
            }
          case 92: break;
          case 35: 
            { System.out.println(" CASE         -> " + yytext().toString());token(" CASE        -> " + yytext());
            }
          case 93: break;
          case 36: 
            { System.out.println(" TRUE         -> " + yytext().toString());token(" TRUE        -> " + yytext());
            }
          case 94: break;
          case 37: 
            { System.out.println(" THIS         -> " + yytext().toString());token(" THIS        -> " + yytext());
            }
          case 95: break;
          case 38: 
            { System.out.println(" VOID         -> " + yytext().toString());token(" VOID        -> " + yytext());
            }
          case 96: break;
          case 39: 
            { System.out.println(" BREAK        -> " + yytext().toString());token(" BREAK       -> " + yytext());
            }
          case 97: break;
          case 40: 
            { System.out.println(" CLASS        -> " + yytext().toString());token(" CLASS       -> " + yytext());
            }
          case 98: break;
          case 41: 
            { System.out.println(" SUPER        -> " + yytext().toString());token(" SUPER       -> " + yytext());
            }
          case 99: break;
          case 42: 
            { System.out.println(" TROW         -> " + yytext().toString());token(" TROW        -> " + yytext());
            }
          case 100: break;
          case 43: 
            { System.out.println(" FALSE        -> " + yytext().toString());token(" FALSE       -> " + yytext());
            }
          case 101: break;
          case 44: 
            { System.out.println(" WHILE        -> " + yytext().toString());token(" WHILE       -> " + yytext());
            }
          case 102: break;
          case 45: 
            { System.out.println(" STATIC       -> " + yytext().toString());token(" STATIC      -> " + yytext());
            }
          case 103: break;
          case 46: 
            { System.out.println(" SWITCH       -> " + yytext().toString());token(" SWITCH      -> " + yytext());
            }
          case 104: break;
          case 47: 
            { System.out.println(" TROWS        -> " + yytext().toString());token(" TROWS       -> " + yytext());
            }
          case 105: break;
          case 48: 
            { System.out.println(" RETURN       -> " + yytext().toString());token(" RETURN      -> " + yytext());
            }
          case 106: break;
          case 49: 
            { System.out.println(" IMPORT       -> " + yytext().toString());token(" IMPORT      -> " + yytext());
            }
          case 107: break;
          case 50: 
            { System.out.println(" PUBLIC       -> " + yytext().toString());token(" PUBLIC      -> " + yytext());
            }
          case 108: break;
          case 51: 
            { System.out.println(" EXTENDS      -> " + yytext().toString());token(" EXTENDS     -> " + yytext());
            }
          case 109: break;
          case 52: 
            { System.out.println(" BOOLEAN      -> " + yytext().toString());token(" BOOLEAN     -> " + yytext());
            }
          case 110: break;
          case 53: 
            { System.out.println(" DEFAULT      -> " + yytext().toString());token(" DEFAULT     -> " + yytext());
            }
          case 111: break;
          case 54: 
            { System.out.println(" FINALLY      -> " + yytext().toString());token(" FINALLY     -> " + yytext());
            }
          case 112: break;
          case 55: 
            { System.out.println(" PACKAGE      -> " + yytext().toString());token(" PACKAGE     -> " + yytext());
            }
          case 113: break;
          case 56: 
            { System.out.println(" INTERFACE    -> " + yytext().toString());token(" INTERFACE   -> " + yytext());
            }
          case 114: break;
          case 57: 
            { System.out.println(" INSTANCEOF   -> " + yytext().toString());token(" INSTANCEOF  -> " + yytext());
            }
          case 115: break;
          case 58: 
            { System.out.println(" IMPLEMENTS   -> " + yytext().toString());token(" IMPLEMENTS  -> " + yytext());
            }
          case 116: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java AnalisadorLexo [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        AnalisadorLexo scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new AnalisadorLexo(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
